### ISSUE TITLE
Notifications remain visible although messages were read.

### ISSUE THREAD

**Issue by feddnoai** [oxen-io/session-desktop#1401]
OS: MX Linux 19.3 ahs
App version: session-desktop-linux-x86_64-1.4.3.AppImage

Whatever I try, notifications remain visible, although messages were read. I'm quite sure the issue appeared after the last update a few days ago.

Screenshot: https://abload.de/img/session-attachment-20hnkje.png

**Comment by Bilb** [comment]
The conversation is marked read only when you hit the bottom of the screen on the message list. (i.e, the most recent is visible and you cannot scroll more to the bottom of the screen).
Can you confirm to me that it does not work for you ?

And what happens if you click on the Button to scroll down programmatically (i.e. scroll up a bit on the message list, on bottom right a button should appear to force the scrolling to the bottom)

**Comment by feddnoai** [comment]
Yes, I can confirm that both methods do not work reliably. I just sent loads of test messages and it only worked once. At the moment notifications are still visible again although I scrolled down and clicked the down button.

**Comment by feddnoai** [comment]
I installed the new version today and at the moment it seems as if the issue is solved! Thank you and fingers crossed! ;)
