### ISSUE TITLE
Groups Tab 

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#1433]
Not sure if something like this has been planned for next release or in the future, but may be it would be nice to put groups and conversations in two different tabs (vertical left buttons) that there is more distinction between 1on1 chats and group chats.

**Comment by reactshow** [comment]
Kind of related, someone in Session feedback also suggested custom group icons so that it is easier to find different groups. I believe they must be talking about closed groups, since open once already have custom icons.

**Comment by FatBirdie** [comment]
Yeah, custom icons would be nice to.

**Comment by Bilb** [comment]
We used to have them separated but this was not convenient. We merged them all together and added a search logic to find what you are looking for quickly

**Comment by ianmacd** [comment]
I wouldn't necessarily want separate tabs, because that would require a click to move from one to the other, but some visual separation between 1-to-1 chats, closed groups and open groups is desirable; with the option to hide/archive certain conversations until they receive a new message.

My left pane is becoming very cluttered now, and whilst the search function helps, it's a lot of typing just to be able to move around one's chats.
