### ISSUE TITLE
[Feature Request] Mute notifications feature on desktop

### ISSUE THREAD

**Issue by reactshow** [oxen-io/session-desktop#1451]
On my android device I have options to mute notifications for specific sessions. This seems not to be possible on desktop (at least Linux). This would be a very nice feature to have as e.g. joining a open group can give you a lot of notifications which can be a bit annoying. But at the same time I would like to be able to have notifications for closed sessions. 

* Device: [Desktop]
* OS: [Linux]

**Comment by beantaco** [comment]
This feature already exists as a general setting:

The settings icon (the cog/wheel) on the left pane -> Notifications -> Mute notifications

However, as you have raised, mute notifications for a specific session does not exist in Session Desktop (Linux).

May I suggest you rename the title of this issue to "[Feature Request] Session-specific mute notifications" or something similar so that people know you mean session-specific mute notification?
