### ISSUE TITLE
Desktop Application flagged as PUA: WIn32/Coinminer

### ISSUE THREAD

**Issue by uncannyjish** [oxen-io/session-desktop#1460]
I have downloaded the application from the trusted sources provided on your website. However, as the file is downloaded completely, defender pops up with a message stating that your application is infected. The details of the virus state that it is a PUA: Win32/Coinminer. I hoped that this will be fixed eventually through updates but this issue is persistent in the last two updates.

If this is a false alarm, please post a virustotal report or something substantial to debuk the claims on your website.

**Comment by KeeJef** [comment]
This flag from Windows Defender is completely false, We suspect that the app is being flagged because of some of the Proof of work code we forked from Bitmessage, which is used before 1-1 and closed group messages are sent to produce a small proof of work attached to the message to protect the network from spamming. 

We will be making some changes in the next few weeks with the next hardfork, which may allow use to remove some of the code that we think is causing this flag.

**Comment by Bilb** [comment]
Closing in favor of https://github.com/oxen-io/session-desktop/issues/1460
