### ISSUE TITLE
How to log out ?

### ISSUE THREAD

**Issue by Many98** [oxen-io/session-desktop#1464]
I cannot find any option to log out and encrypt my session. Everyone with access to my device can read messages.
I was using tox for a while and there it was simple...

**Comment by FatBirdie** [comment]
Logout, or even option to set timeout for Session to lock the chats with passwords would be a nice feature.

**Comment by Many98** [comment]
Finally I found the option to quit session on desktop. It is in menu bar -> File -> Quit Session or just Ctrl+Q. By default menu bar was hidden so I had troubles finding option to log out / quit.

**Comment by beantaco** [comment]
If received messages are stored unencrypted, that is a concern. The private key and recovery phrase are unprotected, so storing just the messages encrypted doesn't help. Not only can someone who accesses the device (physically or remotely) read the user's messages, they can also steal the user's Session identity.

Some way to conveniently encrypt all the user's Session profile data is needed. I know KeePassXC encrypts everything with a password or keyfile.

**Comment by beantaco** [comment]
I'll add some comments about what this this issue is concerned about: security of data stored on devices. Recent messages in one of the Session open groups discuss about various issues with data stored on devices. I don't think I understand the issues properly and have not verified anything, but my understanding of what I read is:

- If no PIN is set, Session uses a fixed key to encrypt messages.
- Messages are stored in an sqlite database, but messages persist in the database even after the user attempts to delete the messages through the UI.
- Some other information persists even after they become obsolete. For example, group name persists even after the user leaves a group.
- Attachments (images, binary files, ...) are stored in `<session-data-path>/attachments.noindex/` unencrypted. (`<session-data-path>` is typically `~/.config/Session` on Linux.)

What I think Session should do:

- Encrypt everything (messages, attachments, contacts, groups, private key, recovery phrase, ...) with the user's PIN/password if set.
- Delete all obsolete content, as soon as possible.

What users could do:

- Use full disk encryption to prevent unwanted physical access to all data.
- Encrypt `<session-data-path>` to protect all Session data. (Warning: Do this at your own risk. This may cause strange issues. Keep your recovery phrase somewhere safe. Securely delete Session folder then wipe free space after encrypting.)

**Comment by beantaco** [comment]
Some issues were created that are based on the open group chat and are related to storing Session's content unencrypted:

- #1550: "Deleted" messages persist in `db.sqlite`.
- #1551: Attachments are stored in `attachments.noindex/` unencrypted.
- #1552: Names of visited groups persist in `db.sqlite`.

I think this issue should remain as a request for a log out feature that encrypts contents upon log out.

**Comment by KeeJef** [comment]
This issue seems defunct, you can logout by setting a password and then quitting the application. Messages are then encrypted with that password, we are working on attachment encryption separately so i'm going to close this
