### ISSUE TITLE
The groups visited remain in the database for life

### ISSUE THREAD

**Issue by jimgillo** [oxen-io/session-desktop#1552]
When you enter a public group, its name is stored in the database (db.sqlite). when you leave it the group name remains in the database. you should delete this data when groups are left.

**Comment by KeeJef** [comment]
We are looking into this

**Comment by Bilb** [comment]
@jimgillo this issue should be fixed with the new open group servers. 

In all cases, this database is encrypted so you need the passphrase to read which groups the user was into.
The db entry should be removed when you leave the an opengroup v2 room. 
This is still not the case for opengroupv1 but we don't support them anymore.

Feel free to reopen if it still happens for you.

**Comment by jimgillo** [comment]
>In all cases, this database is encrypted so you need the passphrase to read which groups the user was into.

this is not true for users who do not put passwords since the fixed key is accessbile in the config.json file and since you do not want to put mandatory passwords, many users will leave everything by default ( without password) and therefore the list of groups will be easily accessible to the police for example.

**Comment by Bilb** [comment]
yeah true. Well this should not happen with v2 rooms anymore
