### ISSUE TITLE
Windows detects session as virus

### ISSUE THREAD

**Issue by lenincritus** [oxen-io/session-desktop#1668]
**Describe the bug**
I downloaded the signal.exe file from getsession.org, tried to install session by opening the executable, the .exe file is detected as virus by windows defender and hence it won't install. When scanned with windows defender it gives the following description of virus: PUA:Win32/CoinMiner

**To Reproduce**
1. Download signal.exe from official site
2. Try to install signal by opening the executable
3. It won't install because it contains virus
**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: Laptopn
* OS: Windows 10
* Session Version or Git commit hash: 1.6.3

**Comment by lenincritus** [comment]
I'm a bit pessismistic about this, is session really safe or it's just a coinminer eating up device's resources? Should i install it or should i wait until the devs remove the "coinminer part"?

**Comment by JakeJMattson** [comment]
This is a false detection by Windows. You can read more about it in Issue #1426 or #1460.

"probably because of some of the cryptographic operations we perform to prevent message spam on the network"

They are looking to fix this: 

"We will be making some changes in the next few weeks with the next hardfork, which may allow use to remove some of the code that we think is causing this flag."

Session is safe, but if you're skeptical, maybe wait until whatever it is in the codebase can be removed.

**Comment by Bilb** [comment]
Closing this in favor of https://github.com/oxen-io/session-desktop/issues/1460
