### ISSUE TITLE
Questions about Session

### ISSUE THREAD

**Issue by hardBSDk** [oxen-io/session-desktop#1695]
I have been using Session Desktop/Android for 4 months (I think) and I have some questions:

1 - I saw that an UI change is on the road, how deep the change is? a new UI implementation replacing the Signal ones or just changes above of it? do you have any plans to port/fork Telegram/Matrix clients UI code?

This additition would be a pleasure, having the Telegram UI solve many feature requests and bring more users/devs (I think) to the project, but I don't know how much work is necessary to fork/adapt the Telegram UI code for Loki blockchain and how the maintenance cost will be.

2 - How much file size limit will be after complete Session implementation?

3 - How voice calls will be implemented in the blockchain? will be pieces of transactions that complete end-to-end?

4 - What about a generic Session library to implement any frontend above of it?

5 - Do you have plans to support non-chat features, like channels and bots? like Briar does (without media support) and Telegram? supporting the Telegram API maybe?

My suggestion to implement channels is to create a specific group where just admins can type, then implement other features above this template.

For bots, I think they can be a separate wallet inside the creator device or just an inline algorithm that provide you search features (like Telegram does) and is downloaded on your device, not relying on third-party servers to work.

6 - Internal forwarded messages/music player

Would be nice to have internal forwarded messages, as your private chats use the same storage zone, the messages from a "Saved Messages" or private bot chat could be forwarded to a group/one-to-one conversation without losing the owner topic, like Telegram does.

And an internal music player like Telegram, where all the audio files of a conversation can be accessed in a playlist and played with special playback options, that continues to play even out of the chat and app.

**Comment by KeeJef** [comment]
> 1 - I saw that an UI change is on the road, how deep the change is? a new UI implementation replacing the Signal ones or just changes above of it? do you have any plans to port/fork Telegram/Matrix clients UI code?

On iOS we have already overhauled the conversations screen and we are currently in the process of making the same changes on Android, elements of those refactors will make their way to desktop too. We aren't planning to fork Telegram or Matrix UI code, from my understanding. 

> 2 - How much file size limit will be after complete Session implementation?

The limit at ~10mb right now is stemming from limitations in the Onion requests protocol, once Lokinet is implemented the limitation can come off, but we still need to have some reasonable limitation on the file storage server to prevent our costs from getting out of hand, 25 MB seems to be a good middle ground. 

> 3 - How voice calls will be implemented in the blockchain? will be pieces of transactions that complete end-to-end?

They aren't implemented in the blockchain, voice calls are effectively real time Lokinet Sessions between two clients where they stream voice call data to eachother. 

> 4 - What about a generic Session library to implement any frontend above of it?

We have thought about it, but its currently not a priority, there are some non official client implementations, like the Session node client 

>  5 - Do you have plans to support non-chat features, like channels and bots? like Briar does (without media support) and Telegram? supporting the Telegram API maybe?

People are building bots already, mostly for open groups though, node client is probably the best place to start for that https://github.com/hesiod-project/node-session-client there isnt any supported API's yet, and its unclear how that would work since we do not provide a central gateway for the sending/receiving of messages 

> My suggestion to implement channels is to create a specific group where just admins can type, then implement other features above this template.

Read only / Admin only posting channels is something that is on the roadmap and should happen pretty soon. 

> 6 - Internal forwarded messages/music player

Message forwarding is interesting, i don't know if it is entirely congruent with our goals, but its something we have thought about before

> And an internal music player like Telegram, where all the audio files of a conversation can be accessed in a playlist and played with special playback options, that continues to play even out of the chat and app.

This would be a stretch goal, something that we might implement eventually but not a priority right now

**Comment by hardBSDk** [comment]
Thanks for answering.
