### ISSUE TITLE
Reply issue

### ISSUE THREAD

**Issue by FatBirdie** [oxen-io/session-desktop#1766]
![issue](https://user-images.githubusercontent.com/40865389/124379616-6ca86300-dcb8-11eb-868e-223cf32c3603.gif)

Couldn't upload a screen capture to git as mkv. Had issues converting it, so I uploaded an mkv but renamed the file ending to .gif (run it in video player)

There is one message that can not be replied to. No apparent errors.
I've tried checking the logs again, but as before there is issues with the log window. Last issue I tried to get logs for, Session crashed. This time, it just says "loading..." so can unfortunately not provide any more details.

**Comment by Bilb** [comment]
Hey, I have an idea about from where this issue might be coming from, but I would need a message with the issue.
Did you see this issue recently on one open group ?

**Comment by eyeberic** [comment]
I have encountered this issue in previous version. 
Previously, I was not able to reply to a message (in the same scenario) sent by another user because they said they have deleted the message from their end, even though it was still delivered and visible on mine.

**Comment by eyeberic** [comment]
@Bilb - Just encountered the issue again in the "Session" open group. 

The sender (Desktop - macOS) sent the message, as indicated by the red arrow. 

![Cannot_Reply](https://user-images.githubusercontent.com/88373201/129151675-5e11f47f-13d1-4bb3-afeb-ff6f243f1a1d.png)

(Message in question, from the Sender's POV)

![Marky_View](https://user-images.githubusercontent.com/88373201/129152376-40532a5c-f94d-4ce3-806c-e8720a3d069f.png)

The sender is able to reply to their own message, and I can reply to their sub-reply. 

![Sender_Can_Reply](https://user-images.githubusercontent.com/88373201/129151482-dfe5f4e0-611f-4fd6-b4e6-898b42c3e2f1.png)

The message is also visible on my end (Desktop - Linux) but nothing happens when I right-click and select "Reply to message". 

**Message details (if required for trace-back):**
- Sent: Thursday, August 12, 2021 2:27 PM (1628749635641)
- Received: Thursday, August 12, 2021 2:27 PM (1628749642533)

**Comment by Bilb** [comment]
@eyeberic 
Can confirm it works on my current dev branch, so I would say this bug is already fixed.
I'll include my latest changes in the next release. Let me know if after you got the next release this still happens to you.

![gif](https://user-images.githubusercontent.com/1544279/129157012-09f79b09-9390-4ddb-a2c2-b32405a00216.gif)
