### ISSUE TITLE
Add function in profile "Save Qr Code to Device"

### ISSUE THREAD

**Issue by ghost** [oxen-io/session-desktop#1860]
Now we can show Qr code but not can saved this image to filesystem.

**Comment by Bilb** [comment]
Might not be that easy, because the renderer process on electron cannot write to the filesystem.

Add a button in `EditProfileDialog` when `qrView` is true which sends what needs to be saved to the filesystem through ipc with https://stackoverflow.com/questions/64819888/is-there-a-way-to-save-write-a-text-file-in-the-renderer-process-without-opening

**Comment by KeeJef** [comment]
Added
