### ISSUE TITLE
*Feature Request* Adding unofficial Open Groups To the Discovery

### ISSUE THREAD

**Issue by Flam3z** [oxen-io/session-desktop#1875]
*This feature should obviously also be applied to android and ios*

There are not many open groups that are advertised to users who want to find other people who have similar interests. A great way to solve this discovery issue is to possible get "unofficial" open groups added under a new column under the "offical open groups" one. Finding an open group not related to oxen takes a little digging or needing to "know someone" in order to find a link to a basic site where unofficial open groups are advertised. I'm open to suggestions and any tweaks or comments about my overall feature request.

**Comment by eyeberic** [comment]
There is already a couple of sites listing Open Groups, which is commonly provided as a response to those asking about it. 

As copied from the Session open group: 

> 🔍 Some list of other Open Group(s) for certain language / theme / topic: 
> https://sessiongroups.com/
> http://lokilocker.com/Mods/Session-Groups/wiki/Session-Open-Groups
> https://session.directory/
> 
> To join an Open Group: 
> * Desktop: Click on "Join Open Group" at bottom-left corner of the app
> * Mobile: On Session app main screen bottom-half, tap on (+) icon, then tap on 🌐 icon (Looks like Internet)
> Copy-paste the Open Group link into the text field, and hit "Next"
> 
> To leave an Open Group: 
> * Desktop: In the Conversation list column, right-click on the group, then select "Leave Group" 
> * Mobile: On Session app main screen, long-press (Android) / swipe (iOS) on the group for more options, tap on "Delete"
> 

If any Open Group is to be listed officially, I would think that it is only if they are subscribed to Oxen hosting on their behalf instead (Session Pro?), which may or may not be subjected to content review since it would not be ideal if Oxen hosted / promoted an Open Group that has "inappropriate" content.

**Comment by Flam3z** [comment]
that could make more sense, in that case users could be warned that the official groups are not monitored/moderated by "Oxen" and to enter at their own risk as inappropriate content may be seen.

**Comment by KeeJef** [comment]
Although this would be cool, I would be very worried about which channels would be included and the moderation of such channels. If we add unofficial groups in the discovery pane we may imply that we support the content in those open groups. This can become a problem for app review and the general impression of the Session app, the current method of out of band discovery is working okay right now, with sites like https://Sessiongroups.com and https://session.directory/

**Comment by Flam3z** [comment]
@KeeJef thanks for your input, I totally forgot about how strict appstores are in that department.

**Comment by ianmacd** [comment]
> Although this would be cool, I would be very worried about which channels would be included and the moderation of such channels. If we add unofficial groups in the discovery pane we may imply that we support the content in those open groups. This can become a problem for app review and the general impression of the Session app, the current method of out of band discovery is working okay right now, with sites like https://Sessiongroups.com and https://session.directory/

The desktop client, at least, is not subject to the censorship of big tech's software clearing houses. There's no store for it to be banned from.

Personally, I'd rather have a seamless open group experience than care about the opinion of those who don't understand that collation and facilitation don't imply endorsement. If movie producers and magazines can get away with boilerplate text disclaiming responsibility for the views contained within their media, why can't the producers of a chat client?

If one of Session's selling points is that it is censorship-resistant, isn't that point undermined by deliberately keeping the UX clunky in order to highlight the boundary between the software and the content? Because forcing OOB group discovery is, at the end of the day, a clear case of allowing a political motive to dictate the choice of an inferior technical solution. That effectively amounts to self-censorship, which I believe is never a good idea and never yields a positive outcome.
