### ISSUE TITLE
Manually deleted chats and messages gets restored when linking / recovery

### ISSUE THREAD

**Issue by eyeberic** [oxen-io/session-desktop#1887]
### Describe the bug

Currently, manually deleted chats (and its contents) gets restored when linking a device, or during ID recovery: 

- 1-to-1
- Closed group
- Open group

It seems like the "Delete" function is only applied to local copy, and does not update the network swarm to remove the relevant data as per user's request. 

While a true real-time sync across multi-device is currently not implemented, this "bug" means that the network swarm is not kept updated with the "latest revision", which then gets synced downstream to a new device being linked / restoring the Session ID. 

### To Reproduce

Starting from the desktop conversation list view: 

- Right-click on a 1-to-1 chat
- Select the "Delete" option
- The 1-to-1 chat is removed from the conversation list
- Either logout by clearing local data only, or use another instance of Session desktop
- Choose to "Link Device" or "Resume Session"
- Submit recovery phrase
- Let the client poll to sync downstream from network swarm
- The 1-to-1 chat that was deleted previously gets restored as well

### Screenshots or Logs

N.A

### Other information

* Device: Linux (AppImage)
* OS: Ubuntu 18.04.01
* Session Version or Git commit hash: 1.6.11
* Related issues: [Desktop #396](https://github.com/oxen-io/session-desktop/issues/396), [Desktop #420](https://github.com/oxen-io/session-desktop/issues/420), [Android #407](https://github.com/oxen-io/session-android/issues/407), [Android #535](https://github.com/oxen-io/session-android/issues/535)

**Comment by Bilb** [comment]
We are currently working on an unsend endpoint which will fix that issue

**Comment by KeeJef** [comment]
This should be fixed for message deletion now since adding & using the unsend endpoint

**Comment by gevvan** [comment]
In my humble opinion this is BY FAR the worst bug in Session.

It makes the so called "security" of this messaging platform a joke, since manually deleted messages (as well as per timer self-destructed ones) is simply brought back to life by just linking a new device, so anyone who has/gets access to your recovery phrase can simply lay hands on all your gory little secrets.

Also, as my testing shows, the 14 day rule is not always present, sometimes way older chat history reveals itself by linking a new device. This leads me to a follow-up question, namely how well secured is the recovery phrase in-app? Say you have Session access-protected with bio metric or pass code, is the passphrase encrypted inside the app data so that a "l33t h4x0r" can't simply extract it in plain-text form from the /data/folder of the app? The same question of course revolves the Windows version of the app?

Anyhow, can developers please try and address this issue instead of looking at real first-world problems like message truncation or whether non SSL http:// links should be previewed or not. I mean, come on, the app is targeting security, trying to win market out of Signal / Telegram / Wickr and suchlike solutions, but still none of the mentioned apps suffers from this hugely severe security issue. Is it really that hard to fix?

**Comment by KeeJef** [comment]
Messages manually unsent from a conversations will be removed from the Service Node network and the devices in the conversation this has been the case since August, if that's not occurring please open an issue and provide logs. 

Regarding disappearing messages, we are in the process of completely overhauling this currently, with the goal that messages which disappear locally will also disappear from the Service Node network. Hoping to be able to push out this new version of disappearing messages soon. https://github.com/oxen-io/session-desktop/pull/2660

Regarding the security of your private keys, on mobile devices keys will be stored inside the system keychain, which will be as secure as the system Session operates on. For desktop you can also encrypt your account at rest with a password which protects the seed from being pulled out from the database.

Messages being restored more than 14 days after being sent shouldn't be occurring, except potentially in the case of message requests done via SOGS. If this is occurring please file an issue.
