### ISSUE TITLE
Invalid Password with Correct Password

### ISSUE THREAD

**Issue by starlightromero** [oxen-io/session-desktop#1940]
I am getting "invalid password" with the correct password. This happened when I upgraded from 1.7.1 to 1.7.3 (I skipped version 1.7.2)

* Device: Macbook Pro 14,2
* OS: Manjaro 21.1.4 (Kernel 5.10.68-1)
* Session Version or Git commit hash: 1.7.3

**Comment by KeeJef** [comment]
This could be hard to diagnose because we don't have anyone else reporting this with a reproducible case, we did have an issue a few months back which was caused by certain chars being used in passwords. When was your password set? does it contain non English characters or anything strange that you think might trip up the client?

**Comment by starlightromero** [comment]
It was set at least 5 months ago, possibly longer.

It contains only English uppercase, lowercase, and numbers

**Comment by Bilb** [comment]
Is this still happening? If yes please reopen
