### ISSUE TITLE
(Feature request) Group option: Only experienced can send images

### ISSUE THREAD

**Issue by peepo5** [oxen-io/session-desktop#2008]
**Problem**
New users can spam bad images and can raid groups and communities.

**Proposed solution**
A solution could be a trust system, so they would have to have been in the group for, lets say, 10 minutes to post images, or would have had to send 50 messages with a maximum of 2 per minute to have permissions for images in the group. This would make raids less common because people would have to invest a considerable amount of time just to be removed.

**Extra info**
I understand this is reliant on features that do not exist yet, like roles, permissions etc, but it is an idea I want to pass because matrix has had this problem and it would be good to have a way to minimize this problem with bad actors.

**Comment by Bilb** [comment]
Hey, is it for opengroups only?

**Comment by peepopoggers** [comment]
I am not sure what you mean but just for groups in general

**Comment by KeeJef** [comment]
This seems like a open group/community specific thing, since in closed groups users must be manually invited to the group by an existing member so spam is much less likely. We do have a plan support this functionality in communities using a bot which connects to https://github.com/oxen-io/session-pysogs , it may be better to raise this issue there, closing this for now
