### ISSUE TITLE
Previously joined open groups do not come back after restore or linked device.

### ISSUE THREAD

**Issue by DillFrescott** [oxen-io/session-desktop#2143]
**Describe the bug**
Previously joined open groups do not come back after restore or linked device. I noticed this with the iOS app too, and subsequently made an issue on that repo as well.

**To Reproduce**
Join an open group, reset device or connect new desktop device, the open groups won't show back up.

**Screenshots or Logs**
n/a

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 11 Pro 64 bit
* Session Version or Git commit hash: Every version I've tried including the newest builds at the time of this issue post.

**Comment by Bilb** [comment]
When you restore a device, we join only the opengroups found in the first configuration message we find on the network. If this message has  no opengroups in it, none are joined.
In the future we might try to keep only the most up to date configuration message in the network but right now this is not possible. 
So for now, this is not a bug, but by design.
