### ISSUE TITLE
Links previews enabled even while being disabled

### ISSUE THREAD

**Issue by LittleBigTea** [oxen-io/session-desktop#2220]
**Describe the bug**
When sending a message containing a link, the link preview will still appear even tho the setting is turned to off.  Only happens when the message contains anything more than the link itself.

**To Reproduce**
Send a text message containing a link

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/81515107/159135201-98e5a899-423e-4154-8108-41fd22b19392.png)

**Other information (please complete the following information):**

* Device: PC, Phone
* OS: Windows 10, Android
* Session Version or Git commit hash: v 1.7.7

**Comment by Bilb** [comment]
Hey,

Link previews do not leak any metadata on the recipient side (unless you open the link in your browser ofc).
That's why they show up here, you being the recipient.

Link previews can only be enabled/disabled on the sender side, as this is the one leaking metadata to the website to build the link preview. What you get as a recipient is the image and the title + domain in the message directly. No requests are made to the domain in question.
So this is actually the expected behavior
