### ISSUE TITLE
Update electron to support native wayland

### ISSUE THREAD

**Issue by BirdInFire** [oxen-io/session-desktop#2294]
When trying to launch the desktop version with electron's wayland's code it doesn't even start.

Please update to a version electron who work on wayland's too.

Thanks !

(Fedora 36 on native Wayland)

**Comment by BirdInFire** [comment]
add info, it seem the bug is majority on the NVIDIA side : Passthrough is not supported, GL is egl, ANGLE is
on intel ship wayland startup (even if buggy but not more than signal so).
Thanks for the help

**Comment by Bilb** [comment]
Hey,
Sorry for the delay.
Are you sure the issue is related to electron version?
It seems electron supports wayland since v12. We have v17 and Signal v19.

And there is only a 2 months difference between v19 (1 month ago https://www.electronjs.org/releases/stable#19.0.0) and  v17.1.2 (3 months ago https://www.electronjs.org/releases/stable?version=17&page=2#17.1.2)

**Comment by ngrigoriev** [comment]
Latest 1.12.3 still runs with xwayland.
