### ISSUE TITLE
publish OpenPGP / gpg fingerprint of APT signing key

### ISSUE THREAD

**Issue by adrelanos** [oxen-io/session-desktop#2309]
I found instructions for adding an APT repository (https://github.com/oxen-io/session-desktop/issues/1397#issuecomment-754945698) but I couldn't find the gpg fingerprint for verification. Could you please publish it one the Sessions website?

**Comment by KeeJef** [comment]
Yeah its here [https://deb.oxen.io/pub.gpg]( https://deb.oxen.io/pub.gpg) & you can go here to find more info on our .deb packages [https://deb.oxen.io](https://deb.oxen.io) , But i think we should make it more clear on the official getsession.org website where to get the debs packages, added to my backlog

**Comment by fabutastic** [comment]
[adrelanos](https://github.com/adrelanos)
>I found instructions for adding an APT repository but I couldn't find the gpg fingerprint

[KeeJef](https://github.com/KeeJef)
> Yeah its here https://deb.oxen.io/pub.gpg 

deb.oxen.io/pub.gpg is the signing key, it is not a published fingerprint. We need a fingerprint published so that we can verify that the downloaded key at https://deb.oxen.io/pub.gpg has not been tampered with. Can you please verify that the fingerprint of the key is `6636 1D8E 3C96 E41C 6DCB  7051 C499 2CE7 A88D 4262`?

```
gpg: keybox '/home/user/.gnupg/pubring.kbx' created
pub   rsa4096/C4992CE7A88D4262 2015-10-28 [SC]
      Key fingerprint = 6636 1D8E 3C96 E41C 6DCB  7051 C499 2CE7 A88D 4262
uid                            Jason Rhinelander <jason@imaginary.ca>
sub   rsa4096/D3778FABF1D6D4A6 2015-10-28 [E]
```

Please confirm

**Comment by KeeJef** [comment]
Yes that fingerprint is correct, `66361D8E3C96E41C6DCB7051C4992CE7A88D4262` is the fingerprint of Jason's GPG signing key. 

Jason's full GPG signing key is also available in several locations 

 - the oxen-io/oxen-core repository, at /utils/gpg_keys/Jason.asc
 - OpenPGP key servers (Jason Rhinelander <jason@session.foundation>, A88D4262)
 - https://imaginary.ca/public.gpg
 - https://github.com/jagerman.gpg
