### ISSUE TITLE
security: NPM found 91 vulnerabilities

### ISSUE THREAD

**Issue by adrelanos** [oxen-io/session-desktop#2322]
This is the output of NPM.

```
found 91 vulnerabilities (8 low, 26 moderate, 42 high, 15 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

For the more general question how to mitigate supply chain attacks, I've created:
`session private messenger does not consider supply chain attacks yet?` #2321

**Comment by mdPlusPlus** [comment]
This actually seems like a big issue, especially since there are 15 known *critical* vulnerabilities.  
Hopefully someone from the team can report back.

**Comment by Bilb** [comment]
We use `yarn` and not `npm` on session-desktop.
It's important, because each of those two tools create a different .lock file, where the specific versions of each packages in use are pinned. So, if you want to do an audit of the packages used, you need to run `yarn audit`.

running `yarn audit` instead of `npm audit` reports 
```
18 vulnerabilities found - Packages audited: 1421
Severity: 2 Moderate | 15 High | 1 Critical
```

In the meantime, I made a PR  to fix the high & critical ones https://github.com/oxen-io/session-desktop/pull/2654
