### ISSUE TITLE
[Feature Request] Note to self on Device Link

### ISSUE THREAD

**Issue by DavidPeet8** [oxen-io/session-desktop#2340]
This issue pertains to how multi device support is handled with Session. From my understanding, it is not technically feasible to disable multi device for a given Session ID, and it is also not possible to guard device linking with 2FA - correct me here if I am wrong.

To link a new device to your Session ID, you only need to provide the correct recovery phrase. I understand that the recovery phrase is quite long and the probability of an attacker stumbling upon your recovery phrase is very low. That said, I think the unlikely case that an attacker stumbles upon any user's recovery phrase has some issues:
1. When a new device is linked to a Session ID, the owner of that ID will never know. Thus an attacker can silently listen into communication.
2. If the generation of recovery phrases happens to have a bug in the future, an attacker could exploit this to generate recovery phrases for Session IDs that are actively being used. 

**Suggestion:** As an alternative to 2FA, would it be feasible to make session clients send a "Note to self" whenever a new device is linked? I realize that an attacker could ad-hoc their own Session client that does not generate such messages to secretly listen in, but I feel that this feature raises the bar to entry.

**Comment by KeeJef** [comment]
Covered by #2180 

> quite long and the probability of an attacker stumbling upon your recovery phrase is very low. That said, I think the unlikely case that an attacker stumbles upon any user's recovery phrase has some issues:

The chance of randomly choosing the same Session private key as another user is so exceedingly improbable that we don't really have to worry about it, we have essentially the same cryptographic guarantees as someone generating your Bitcoin wallet keys randomly. 

However this is still a risk we would like to mitigate in the event that someone steals your keys and wants to monitor new messages.

**Comment by dm17** [comment]
Does Oxen somehow detect bruteforce / exhaustive attacks on accounts? This is the only Session thread I've found for the 2FA keyword so I figured it would make sense to ask here: I figured 2FA could be used to decrease the load in the case of attacks because then you could limit login attempts/failures per user per day to something very low. Has Session made any official responses on why 2FA isn't necessary / just one password is ideal? I'm all for not overcomplicating things, so I'm unsure on this one. I suppose we must really trust the SSL process between each client and server whenever we re-send the recovery code - and if so, then 2FA is much less necessary.

**Comment by KeeJef** [comment]
It's not possible with current computing tech to guess someones seed / recovery phrase. Or are you referring to the local password/pin which a user can set on their account?

**Comment by dm17** [comment]
@KeeJef That's correct - and not saying it is possible to bruteforce - but I did claim that attempts at doing so could stress the Oxen nodes. Or perhaps there's some protection against DDoS in your system? So you see no need for 2FA, right?

Since I'm not sure where else to ask - I'm curious what you think of my suggestion regarding the increasing demand on oxen nodes (i.e. groups are limited to 100). Now I realize that one must pay to have a node - but what if there was some way to pay the oxen network as a user? That kind of load is what prevents Session from wanting an "export all data from my Session account" feature so far, right?

**Comment by KeeJef** [comment]
Brute-forcing the local account password is possible if the password isn't sufficiently complex. Implementing 2FA would require network interactions when the user opens the app to decrypt the db, which could raise privacy and trust concerns. I'm not sure exactly how this would be implemented. 

An alternative approach could be to incorporate a password strength indicator. This indicator would inform users of the strength of their password (strong, medium, or weak) when they set it, encouraging them to choose a more secure option without enforcing requirements.

**Comment by dm17** [comment]
I don't really follow because I'm just talking about the passphrase used to login. Not that interested in the pin to lock session because - as Session devs have pointed out - if the computer is compromised, then we should consider what is on it is also (especially if we don't know and unlock it / input the pin).

I'm talking about the login process where the passphrase is sent via SSL. I do realize the 2FA aspect could make it too complex for Session's purposes. I can start another thread to discuss what might help allow a 'backup/export all chats feature' not so demanding on Session's network (aka Oxen nodes).

**Comment by KeeJef** [comment]
There is no point were a login, recovery phrase or password is sent to the network via SSL or any other method. Messages and configuration data are always decrypted locally, by first downloading the encrypted data from the swarm and then using your keys to decrypt.

**Comment by dm17** [comment]
My misunderstanding; that's elegant! So all of the config/account data any user needs is already downloaded for everyone by the time they enter their recovery phrase! I'll have to dig into how it works exactly sometime.
Thanks!
