### ISSUE TITLE
[Feature request] Enable filtering of messages displayed to a user based on language or charset

### ISSUE THREAD

**Issue by nikmit** [oxen-io/session-desktop#2510]
The events in Iran caused a sudden influx of Farsi speakers to open Session groups in the last couple of days and as amazing as it is that Session can step up and offer a solution to people in need, it made it difficult for the channel to keep functioning as intended without the constant intervention of moderators.
I am not for censorship and moderation is rather time consuming. Enabling additional filters so users can remove irrelevant to them content from open groups seems like a good solution. One obvious filter like that is based on language. Whether this based on full language recognition or just character set will depend on what is technically feasible but in either case should make communicating within an open group much easier and reduce the load/reliance on moderators at the same time.

As an example, being able to filter out anything not written in latin or cyrillic would be a great start.

**Comment by KeeJef** [comment]
So we ended up tackling this with a language detection + the new whisper functionality in PySOGS. If a user sends a message in Farsi into one of the official communities/open groups the message is detected as using Farsi and does not get stored on the PySOGS, the PySOGS then uses a whisper to send a message which only that user can see, which gives them some more information about the rules of the official open groups and some community run Farsi groups they can join. I think this is the best way to handle this, rather than making changes client side. 

Closing this for now, but it might be worth us publishing some docs/article on how we did that on the official SOGS so other SOGS operators can deploy similar solutions.
