### ISSUE TITLE
Feature Request: Password Lock On Account Deletion

### ISSUE THREAD

**Issue by oxenreport** [oxen-io/session-desktop#2615]
as summarized by user: 
I noticed that the password on the desktop side, it seems to be unable to prevent the option to delete the account is intentional? If the settings option requires a password to be entered to change, why not the delete account option? 
Although this only happens if the application is not closed and the person walks away, (if the application is closed, you need to enter the password when you start logging in), it still feels awkward, and obviously the settings cannot be changed, but you have the option to delete the account by entering the wrong password.

**Comment by KeeJef** [comment]
This is intentional, atleast on startup if you fail to enter the correct password three times Session gives you the ability to clear your account. So you can already clear someones account if you have access to their local device but you don't know their password. The user could also just delete Session files locally. Closing this for now as it is intended functionality.
