### ISSUE TITLE
Cannot '@mention' in messages open group users who have not posted since id blinding was enabled on server.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-desktop#2635]
I enabled Session id blinding for `sog.caliban.org` on 2023-01-01 at 00.00 UTC. The server runs PySOGS 0.3.6.

Since then, users who have not yet posted using their blinded Session id cannot be _mentioned_ in messages by typing an `@` symbol, followed by their display name. The list of auto-completing results simply omits the name of anyone who has previously posted only under their unblinded Session id.

A workaround is to mention the user in question by typing an `@` followed by the user's unblinded Session id, if known.

This occurs with Session 1.10.4.

**Comment by Bilb** [comment]
Hey
Yeah, that's by design.
If we didn't remove the unblinded ids from the list of the mentions on the blinded servers, one user might have the 2 results on his client.
If he does (as you suggest) the @unblinded id, everyone will be able to grab the unblinded id of that user.
So to prevent this, we exclude the unblinded ids from the mentions list on a blinded server.

Let me know if that makes sense
