### ISSUE TITLE
[BUG] Session not loading

### ISSUE THREAD

**Issue by skulmet** [oxen-io/session-desktop#2916]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ive used session for a couple of days without problems but since 2 days ago it wont load. After launching the program i only get to the logo screen with the S and then nothing more happens ive let it run for hours and still nothing still stuck on splash screen

### Expected Behavior

The app acutally loading 

### Steps To Reproduce

1. click the shortcut/exe file
2. it not loading

### Desktop Version

v1.11.2

### Anything else?

Windows 11, version 22H2

**Comment by Bilb** [comment]
Can you start it from the terminal somehow and send me the logs it prints?

**Comment by radikalcevreci** [comment]
> Can you start it from the terminal somehow and send me the logs it prints?


C:\Users\kayaktravel\AppData\Local\Programs\Session>SESSion.exe

C:\Users\kayaktravel\AppData\Local\Programs\Session>
Set Windows Application User Model ID (AUMID) { appUserModelId: 'com.loki-project.messenger-desktop' }
NODE_ENV production
NODE_APP_INSTANCE undefined
NODE_CONFIG_DIR C:\Users\kayaktravel\AppData\Local\Programs\Session\resources\app.asar\config
NODE_CONFIG {}
userData: C:\Users\kayaktravel\AppData\Roaming\Session
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
making app single instance
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"app ready","time":"2023-09-22T06:40:37.434Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"starting version 1.11.3","time":"2023-09-22T06:40:37.434Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"locale is en-US","time":"2023-09-22T06:40:37.437Z","v":0}
initializeSql sqlnode
Made sure db folder exists at: C:\Users\kayaktravel\AppData\Roaming\Session\sql
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"updateSchema:","time":"2023-09-22T06:40:37.455Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":" Current user_version: 11","time":"2023-09-22T06:40:37.456Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":" Most recent db schema: 11","time":"2023-09-22T06:40:37.456Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":" SQLite version: 3.39.4","time":"2023-09-22T06:40:37.468Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":" SQLCipher version: 4.5.3 community","time":"2023-09-22T06:40:37.510Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":" (deprecated) schema_version: 221","time":"2023-09-22T06:40:37.533Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"updateSessionSchema: Current loki schema version: 33; Most recent schema version: 33;","time":"2023-09-22T06:40:37.535Z","v":0}
total message count before cleaning:  7
total conversation count before cleaning:  50
cleanUpOldOpengroups: v2Convos is empty
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"attachment_downloads count 0","time":"2023-09-22T06:40:37.572Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"conversations count 50","time":"2023-09-22T06:40:37.573Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"encryptionKeyPairsForClosedGroupV2 count 0","time":"2023-09-22T06:40:37.574Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"guardNodes count 3","time":"2023-09-22T06:40:37.576Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"identityKeys count 0","time":"2023-09-22T06:40:37.576Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"items count 27","time":"2023-09-22T06:40:37.579Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"lastHashes count 4","time":"2023-09-22T06:40:37.580Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"loki_schema count 33","time":"2023-09-22T06:40:37.581Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"messages count 7","time":"2023-09-22T06:40:37.586Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"messages_fts count 10","time":"2023-09-22T06:40:37.589Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"messages_fts_config count 1","time":"2023-09-22T06:40:37.589Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"messages_fts_content count 10","time":"2023-09-22T06:40:37.590Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"messages_fts_data count 6","time":"2023-09-22T06:40:37.590Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"messages_fts_docsize count 10","time":"2023-09-22T06:40:37.591Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"messages_fts_idx count 4","time":"2023-09-22T06:40:37.591Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"nodesForPubkey count 1","time":"2023-09-22T06:40:37.591Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"openGroupRoomsV2 count 0","time":"2023-09-22T06:40:37.592Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"seenMessages count 0","time":"2023-09-22T06:40:37.592Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"sqlite_sequence count 2","time":"2023-09-22T06:40:37.593Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"sqlite_stat1 count 13","time":"2023-09-22T06:40:37.593Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"sqlite_stat4 count 91","time":"2023-09-22T06:40:37.595Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"unprocessed count 0","time":"2023-09-22T06:40:37.595Z","v":0}
total message count after cleaning:  7
total conversation count after cleaning:  50
Vacuuming DB. This might take a while.
Vacuuming DB Finished in 28ms.
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"Ensure attachments directory exists","time":"2023-09-22T06:40:37.627Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"Location reset needed","time":"2023-09-22T06:40:37.639Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"Initializing BrowserWindow config: {\"show\":true,\"minWidth\":880,\"minHeight\":600,\"backgroundColor\":\"#1B1B1B\",\"webPreferences\":{\"nodeIntegration\":true,\"enableRemoteModule\":true,\"nodeIntegrationInWorker\":true,\"contextIsolation\":false,\"preload\":\"C:\\\\Users\\\\kayaktravel\\\\AppData\\\\Local\\\\Programs\\\\Session\\\\resources\\\\app.asar\\\\preload.js\",\"nativeWindowOpen\":true,\"spellcheck\":true},\"maximized\":true,\"autoHideMenuBar\":true,\"width\":1616,\"height\":876}","time":"2023-09-22T06:40:37.640Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"spellcheck: user locale: en-US","time":"2023-09-22T06:40:37.957Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"spellcheck: available spellchecker languages:  [\"af\",\"bg\",\"ca\",\"cs\",\"cy\",\"da\",\"de\",\"de-DE\",\"el\",\"en\",\"en-AU\",\"en-CA\",\"en-GB\",\"en-GB-oxendict\",\"en-US\",\"es\",\"es-419\",\"es-AR\",\"es-ES\",\"es-MX\",\"es-US\",\"et\",\"fa\",\"fo\",\"fr\",\"fr-FR\",\"he\",\"hi\",\"hr\",\"hu\",\"hy\",\"id\",\"it\",\"it-IT\",\"ko\",\"lt\",\"lv\",\"nb\",\"nl\",\"pl\",\"pt\",\"pt-BR\",\"pt-PT\",\"ro\",\"ru\",\"sh\",\"sk\",\"sl\",\"sq\",\"sr\",\"sv\",\"ta\",\"tg\",\"tr\",\"uk\",\"vi\"]","time":"2023-09-22T06:40:37.959Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"spellcheck: setting languages to:  [\"en-US\",\"en\"]","time":"2023-09-22T06:40:37.960Z","v":0}
(node:10364) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Session --trace-deprecation ...` to show where the warning was created)
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"background page reloaded","time":"2023-09-22T06:40:41.341Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"environment: production","time":"2023-09-22T06:40:41.346Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"Storage fetch","time":"2023-09-22T06:40:41.348Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"initializeLibSessionUtilWrappers alldumpsInDB already:  [{\"publicKey\":\"[REDACTED]\",\"variant\":\"UserGroupsConfig\"},{\"publicKey\":\"[REDACTED]\",\"variant\":\"UserConfig\"},{\"publicKey\":\"[REDACTED]\",\"variant\":\"ContactsConfig\"},{\"publicKey\":\"[REDACTED]\",\"variant\":\"ConvoInfoVolatileConfig\"}]","time":"2023-09-22T06:40:41.496Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":50,"msg":"Error received from worker job 6 (ContactsConfig): Invalid session ID: expected 66 hex digits starting with 05; got 059be6f4077df4d211029d329059a32fd4e2a50602a538654cd9d1 ad66bb7f055","time":"2023-09-22T06:40:41.935Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"Worker job 6 (ContactsConfig) failed in 1ms with Error received from worker job 6 (ContactsConfig): Invalid session ID: expected 66 hex digits starting with 05; got 059be6f4077df4d211029d329059a32fd4e2a50602a538654cd9d1 ad66bb7f055","time":"2023-09-22T06:40:41.936Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":50,"msg":"ConversationController: initial fetch failed Error: Error received from worker job 6 (ContactsConfig): Invalid session ID: expected 66 hex digits starting with 05; got 059be6f4077df4d211029d329059a32fd4e2a50602a538654cd9d1 ad66bb7f055\n    at WorkerInterface._worker.onmessage ([REDACTED]\\ts\\webworker\\worker_interface.js:41:31)","time":"2023-09-22T06:40:41.937Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":50,"msg":"main_renderer: ConversationController failed to load: Error: Error received from worker job 6 (ContactsConfig): Invalid session ID: expected 66 hex digits starting with 05; got 059be6f4077df4d211029d329059a32fd4e2a50602a538654cd9d1 ad66bb7f055\n    at WorkerInterface._worker.onmessage ([REDACTED]\\ts\\webworker\\worker_interface.js:41:31)","time":"2023-09-22T06:40:41.938Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"Cleanup: starting...","time":"2023-09-22T06:40:41.939Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"Cleanup: Found 0 messages for cleanup","time":"2023-09-22T06:40:41.941Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"Cleanup: complete","time":"2023-09-22T06:40:41.941Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"listening for registration events","time":"2023-09-22T06:40:41.942Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"connect","time":"2023-09-22T06:40:41.943Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":50,"msg":"Top-level unhandled promise rejection: Error: Error received from worker job 6 (ContactsConfig): Invalid session ID: expected 66 hex digits starting with 05; got 059be6f4077df4d211029d329059a32fd4e2a50602a538654cd9d1 ad66bb7f055\n    at WorkerInterface._worker.onmessage ([REDACTED]\\ts\\webworker\\worker_interface.js:41:31)","time":"2023-09-22T06:40:41.951Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"getAllFromCache","time":"2023-09-22T06:40:51.952Z","v":0}
{"name":"log","hostname":"DESKTOP-8ST2MM8","pid":2156,"level":30,"msg":"getAllFromCache loaded 0 saved envelopes","time":"2023-09-22T06:40:51.954Z","v":0}

**Comment by Bilb** [comment]
Hey, that seems to be the same bug as https://github.com/oxen-io/session-desktop/issues/2872
I'll work on a fix

**Comment by Bilb** [comment]
Hey, do you have a way to test an binary before I merge it?
