### ISSUE TITLE
Disappearing messages setting forgotten by client after reinstalling

### ISSUE THREAD

**Issue by qdhj** [oxen-io/session-desktop#3047]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I reinstall the app, message self-deletion timer drops to default (off), while still stays for my recepient.

### Steps To Reproduce

1. Alice starts the self-deletion timer with Bob
2. Bob deletes the app and installs it again
3. Alice still has the timer, the Bob does not

As far as I understand, even if the Bob started the timer, he can still reinstall the app and drop it, still leaving it for Alice

### Desktop Version

v.1.12

**Comment by KeeJef** [comment]
I think there a little confusion about the new disappearing messages feature. Since the update of disappearing messages the setting is per user, instead of per conversation, allowing one person to set a timer (like 5 minutes) and another to not set one at all.

To sync timers with someone else, you can use the "Follow Settings" option which appears in the conversation when someone changes their setting, which adjusts your timer to match theirs. Your chosen timer setting is saved and will be restored if you recover your account from a seed, as long as you were online in the last 30 days.
