### ISSUE TITLE
[BUG] Session desktop crashes on launch with libsession_util_node error after update to 1.12.5 on macOS

### ISSUE THREAD

**Issue by sysfu** [oxen-io/session-desktop#3128]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Session crashes on launch with popup error complaining that libsession_util_node was built for macOS 12.7

### Expected Behavior

Session launches normally after completing autoupdate and restarting the application.

### Steps To Reproduce

Complete auto-update to 1.12.5
Restart Session
Observe Session crash on application launch

### Desktop Version

1.12.5

### Anything else?

macOS 
macOS 10.15.7

![Screen Shot 2024-07-23 at 4 00 44 PM](https://github.com/user-attachments/assets/02530d20-fd4a-40a9-a662-76f7001c0fd9)

**Comment by Bilb** [comment]
Hey, can you confirm that you are indeed running macos 12.15.7 and not macos 10.15.7. I couldn't find such a version online

**Comment by sysfu** [comment]
I'm sorry that was a typo, the system is running macOS Catalina 10.15.7. 

Why was support for Catalina dropped with the 1.12.5 release?

The previous one supported it.

**Comment by Bilb** [comment]
The support of Catalina was dropped because the session desktop binary build is dependent on what version of macos the build is made.
We use the oldest version of macos supported by github actions to build the app. That way, Session can be running on the oldest macos system possible. The macos-11 runner was removed from github actions in June, and is also not supported by Apple anymore. Hence why the support for macos pre-12 has been removed.


https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal
https://en.wikipedia.org/wiki/MacOS_Big_Sur
