### ISSUE TITLE
Future: voice calls? 

### ISSUE THREAD

**Issue by lrq3000** [oxen-io/session-desktop#777]
I know and agree that Loki Messenger should for the moment focus on implementing reliably secure and anonymous text messaging, but since LLARP is meant to be a low latency network, I'm wondering if voice calls (not just voice snippets) are planned in the future? I could see something like Jami E2EE p2p voice protocol but using the loki network for peers discovery (just like for text messages) instead of OpenDHT, and tunneling voice packets through LLARP network to be anonymized?

The idea is not necessarily to copy Jami, it's just a reference that suggests it may be possible to implement anonymous voice calling in Loki Messenger with some conceptual adaptation?

**Comment by KeeJef** [comment]
So theres a couple of things to cover here. 

Lokinet does implement an anonymous network layer, so its fairly easy to setup a peer to peer connection between two users through Lokinet and have them use some VOIP protocol to talk with eachother. Internally we are already using mumble through Lokinet and it works well.

However for the first release of Session/Loki messenger, which will be out in a few days, we have decided to go with a much simpler anon network layer, while Lokinet fixes some issues with its DHT and Router exploration, and we build out mobile clients. The Session release in a few days will not be implementing Onion routing at the network layer instead it does it at the transport layer and uses TCP, this pretty much precludes us from having real time voice coms, since most good VOIP protocols use UDP. 

The eventual plan is to make Session/Loki messenger use Lokinet but it will take some time before we build out mobile clients and resolve all issues with the DHT and Router exploration. So the roundabout answer to this question is, yes Session will have voice calls eventually.

**Comment by lrq3000** [comment]
Thank you for your detailed answer @KeeJef, it's great to hear Session will potentially be able to support voice calls in the future! There is a clear lack of anonymous and secure (and stably working!) messaging apps, and for voice calls it's virtually unheard of or is highly complicated to setup! I'll actively follow and recommend your progress, I think we need the kind of initiative you do to hopefully reach a more free internet :-)

**Comment by wuniversales** [comment]
Great!! And the video calls will also arrive, right?

**Comment by KeeJef** [comment]
Video calls are trickier since the volume of traffic is much higher than a voice call, we have been doing streaming of HD video over Lokinet, however that was on the testnet, it remains to be seen if the regular network can handle that much traffic at scale. Its something we will definitely investigate.

**Comment by KeeJef** [comment]
Closed because calls have now been implemented, Lokinet routed calls will come with liblokinet integration into mobile apps which we are working on
